#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd

echo "
<html>


    <head>

        <title>Simple HTML page</title>

    </head>

    <body>

        This page has been deployed in the {{ Env }} environment!

    </body>

</html> " > /var/www/html/index.html
